#### Variables
@spring-pitfalls-url = http://localhost:8080

## Pokemons
### [V1] Get pokemon by name
GET {{spring-pitfalls-url}}/v1/pokemons/voltorb

### [V2] Get pokemon by name
GET {{spring-pitfalls-url}}/v2/pokemons/voltorb

## Trainers
### [V1] Create trainer
POST {{spring-pitfalls-url}}/v1/trainers
Content-Type: application/json

{
    "name": "Green"
}

## States
###  Get state by uf
GET {{spring-pitfalls-url}}/v1/states/al

### Banks
GET {{spring-pitfalls-url}}/v1/banks/999